import type { Recipe, DailyRecipes } from './types';

// ─── 訓練後食譜（碳水為主，搭配乳清蛋白搖搖杯）───

export const postWorkoutRecipes: Recipe[] = [
  {
    id: 'pw-sweet-potato-oats',
    name: '地瓜燕麥能量碗',
    mealSlot: 'post-workout',
    cookingMethod: '電鍋',
    prepTime: 30,
    macros: { protein: 6, carbs: 75, fat: 4, calories: 360 },
    ingredients: [
      { name: '地瓜', amount: '250g（約1中條）' },
      { name: '燕麥', amount: '40g' },
      { name: '香蕉', amount: '1根' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '地瓜洗淨切塊，放入電鍋內鍋，外鍋1杯水蒸熟',
      '燕麥加熱水泡軟（或微波2分鐘）',
      '香蕉切片',
      '碗中依序放入地瓜、燕麥、香蕉片',
      '肌酸 5g 加入乳清蛋白搖搖杯一起喝',
    ],
    tips: '地瓜可前晚蒸好冷藏，冷地瓜含更多抗性澱粉',
  },
  {
    id: 'pw-banana-oat-bowl',
    name: '香蕉燕麥暖碗',
    mealSlot: 'post-workout',
    cookingMethod: '電子鍋',
    prepTime: 15,
    macros: { protein: 8, carbs: 72, fat: 6, calories: 374 },
    ingredients: [
      { name: '燕麥', amount: '80g' },
      { name: '香蕉', amount: '1.5根' },
      { name: '水', amount: '200ml' },
      { name: '綜合堅果', amount: '10g' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '燕麥 + 水放入電子鍋，選「粥」模式',
      '煮好後放入切片香蕉拌勻',
      '撒上綜合堅果',
      '肌酸加入乳清搖搖杯',
    ],
    tips: '香蕉越熟 GI 越高，訓練後用全熟香蕉加速恢復',
  },
  {
    id: 'pw-sweet-potato-banana-mash',
    name: '地瓜香蕉泥',
    mealSlot: 'post-workout',
    cookingMethod: '電鍋',
    prepTime: 35,
    macros: { protein: 4, carbs: 80, fat: 2, calories: 354 },
    ingredients: [
      { name: '地瓜', amount: '300g' },
      { name: '香蕉', amount: '1根' },
      { name: '碘鹽', amount: '少許' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '地瓜去皮切小塊，電鍋外鍋1杯水蒸至軟爛',
      '趁熱壓成泥',
      '香蕉壓碎拌入地瓜泥，加少許碘鹽提味',
      '肌酸加入乳清蛋白搖搖杯',
    ],
    tips: '少許碘鹽補充電解質，提升風味',
  },
  {
    id: 'pw-oat-sweet-potato-porridge',
    name: '燕麥地瓜粥',
    mealSlot: 'post-workout',
    cookingMethod: '電子鍋',
    prepTime: 40,
    macros: { protein: 7, carbs: 78, fat: 3, calories: 367 },
    ingredients: [
      { name: '燕麥', amount: '50g' },
      { name: '地瓜', amount: '200g' },
      { name: '水', amount: '400ml' },
      { name: '香蕉', amount: '半根' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '地瓜去皮切小丁',
      '燕麥、地瓜丁、水放入電子鍋，選「粥」模式',
      '煮好後拌入香蕉片',
      '肌酸加入乳清搖搖杯',
    ],
  },
  {
    id: 'pw-double-banana-oat',
    name: '雙蕉堅果燕麥',
    mealSlot: 'post-workout',
    cookingMethod: '免煮',
    prepTime: 5,
    macros: { protein: 10, carbs: 70, fat: 8, calories: 390 },
    ingredients: [
      { name: '燕麥', amount: '60g' },
      { name: '香蕉', amount: '2根' },
      { name: '綜合堅果', amount: '15g' },
      { name: '熱水', amount: '150ml' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '燕麥加熱水泡3分鐘',
      '香蕉切片鋪在燕麥上',
      '撒上綜合堅果',
      '肌酸加入乳清搖搖杯',
    ],
    tips: '最快的訓練後碳水方案，5分鐘搞定',
  },
  {
    id: 'pw-sweet-potato-oat-cake',
    name: '地瓜蛋燕麥糕',
    mealSlot: 'post-workout',
    cookingMethod: '電鍋',
    prepTime: 45,
    macros: { protein: 12, carbs: 76, fat: 7, calories: 415 },
    ingredients: [
      { name: '地瓜', amount: '200g' },
      { name: '燕麥', amount: '60g' },
      { name: '雞蛋', amount: '1顆' },
      { name: '香蕉', amount: '半根' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '地瓜蒸熟壓泥',
      '拌入燕麥、打入雞蛋攪勻',
      '倒入內鍋，表面鋪香蕉片',
      '電鍋外鍋1.5杯水蒸熟',
      '放涼切塊食用，肌酸配乳清',
    ],
    tips: '可一次做多份冷藏，隔天微波加熱',
  },
  {
    id: 'pw-overnight-oats',
    name: '隔夜燕麥罐',
    mealSlot: 'post-workout',
    cookingMethod: '免煮',
    prepTime: 5,
    macros: { protein: 16, carbs: 68, fat: 8, calories: 408 },
    ingredients: [
      { name: '燕麥', amount: '70g' },
      { name: '希臘優格', amount: '100g' },
      { name: '水', amount: '80ml' },
      { name: '香蕉', amount: '1根' },
      { name: '綜合堅果', amount: '10g' },
      { name: '肌酸', amount: '5g' },
    ],
    steps: [
      '前晚：燕麥 + 希臘優格 + 水放入密封罐冷藏',
      '早上取出，拌入香蕉片和堅果',
      '直接食用（冷吃或微波加熱皆可）',
      '肌酸加入乳清搖搖杯',
    ],
    tips: '前晚準備，訓練後零等待。優格提供額外蛋白質和益生菌',
  },
];

// ─── 午餐食譜（40-50g 蛋白 + 十字花科蔬菜）───

export const lunchRecipes: Recipe[] = [
  {
    id: 'lunch-chicken-broccoli-rice',
    name: '雞胸花椰菜糙米飯',
    mealSlot: 'lunch',
    cookingMethod: '電子鍋',
    prepTime: 45,
    macros: { protein: 45, carbs: 50, fat: 6, calories: 434 },
    ingredients: [
      { name: '雞胸肉', amount: '150g' },
      { name: '冷凍綠花椰菜', amount: '150g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '大蒜', amount: '2瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米洗淨放入電子鍋，加水，選「糙米」模式',
      '雞胸肉抹鹽、蒜末，用鋁箔紙包好',
      '花椰菜解凍備用',
      '糙米煮到一半時，將雞胸和花椰菜放蒸架上',
      '煮好後雞胸切片擺盤',
    ],
    tips: '一鍋完成飯+肉+菜，電子鍋蒸架是關鍵',
  },
  {
    id: 'lunch-salmon-spinach-rice',
    name: '鮭魚菠菜糙米',
    mealSlot: 'lunch',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 42, carbs: 48, fat: 12, calories: 468 },
    ingredients: [
      { name: '冷凍鮭魚排', amount: '150g' },
      { name: '菠菜', amount: '100g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '檸檬', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米洗淨放內鍋加水',
      '鮭魚退冰後抹鹽，放在糙米上方的蒸盤',
      '電鍋外鍋2杯水',
      '跳起前5分鐘放入菠菜一起蒸',
      '擠檸檬汁在鮭魚上',
    ],
    tips: '鮭魚不需完全退冰，半解凍蒸出來更嫩',
  },
  {
    id: 'lunch-egg-broccoli-rice',
    name: '三蛋花椰菜蓋飯',
    mealSlot: 'lunch',
    cookingMethod: '電鍋',
    prepTime: 35,
    macros: { protein: 42, carbs: 50, fat: 16, calories: 508 },
    ingredients: [
      { name: '雞蛋', amount: '4顆' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '洋蔥', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放電鍋煮飯',
      '雞蛋放電鍋上層蒸架一起蒸（水煮蛋）',
      '花椰菜、洋蔥切好，飯快好時放蒸架蒸5分鐘',
      '水煮蛋剝殼切半，鋪在糙米飯上',
      '花椰菜、洋蔥鋪旁邊',
    ],
    tips: '4顆全蛋提供28g蛋白+花椰菜的植物蛋白補足目標',
  },
  {
    id: 'lunch-chicken-cauliflower-bowl',
    name: '雞胸花椰菜低碳碗',
    mealSlot: 'lunch',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 48, carbs: 35, fat: 5, calories: 377 },
    ingredients: [
      { name: '雞胸肉', amount: '160g' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '糙米', amount: '70g（生重）' },
      { name: '大蒜', amount: '3瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米加水放內鍋',
      '雞胸肉切厚片抹鹽蒜末，放蒸盤',
      '花椰菜放蒸盤旁',
      '電鍋外鍋2杯水一次蒸好',
      '擺盤調味即可',
    ],
  },
  {
    id: 'lunch-salmon-broccoli-sweet-potato',
    name: '鮭魚花椰菜地瓜餐',
    mealSlot: 'lunch',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 40, carbs: 52, fat: 10, calories: 454 },
    ingredients: [
      { name: '冷凍鮭魚排', amount: '130g' },
      { name: '冷凍綠花椰菜', amount: '150g' },
      { name: '地瓜', amount: '200g' },
      { name: '檸檬', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '地瓜切塊放內鍋',
      '鮭魚抹鹽放蒸盤',
      '電鍋外鍋1.5杯水',
      '跳起前5分鐘加入花椰菜',
      '擠檸檬汁提味',
    ],
  },
  {
    id: 'lunch-chicken-egg-spinach',
    name: '雞胸蛋菠菜糙米',
    mealSlot: 'lunch',
    cookingMethod: '電子鍋',
    prepTime: 45,
    macros: { protein: 50, carbs: 48, fat: 10, calories: 482 },
    ingredients: [
      { name: '雞胸肉', amount: '120g' },
      { name: '雞蛋', amount: '2顆' },
      { name: '菠菜', amount: '100g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '大蒜', amount: '2瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放電子鍋煮飯',
      '雞胸肉切薄片抹鹽蒜末，鋁箔包好',
      '雞蛋放蒸架（水煮蛋）',
      '飯快好時放入雞胸包和菠菜',
      '完成後組合成碗',
    ],
  },
  {
    id: 'lunch-avocado-salmon-bowl',
    name: '酪梨鮭魚蛋糙米碗',
    mealSlot: 'lunch',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 43, carbs: 45, fat: 18, calories: 510 },
    ingredients: [
      { name: '冷凍鮭魚排', amount: '120g' },
      { name: '雞蛋', amount: '1顆' },
      { name: '酪梨', amount: '半顆' },
      { name: '糙米', amount: '80g（生重）' },
      { name: '菠菜', amount: '50g' },
      { name: '檸檬', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋煮飯',
      '鮭魚、蛋放蒸盤一起蒸',
      '電鍋外鍋1.5杯水',
      '酪梨切片，菠菜洗淨',
      '組碗：飯底→菠菜→鮭魚→蛋→酪梨，擠檸檬',
    ],
    tips: '酪梨不蒸，最後擺盤保留營養',
  },
];

// ─── 晚餐食譜（40-50g 蛋白 + 纖維→蛋白→碳水順序）───

export const dinnerRecipes: Recipe[] = [
  {
    id: 'dinner-chicken-broccoli-rice',
    name: '蒜香雞胸花椰菜飯',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 45,
    macros: { protein: 46, carbs: 50, fat: 5, calories: 429 },
    ingredients: [
      { name: '雞胸肉', amount: '150g' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '大蒜', amount: '4瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋，雞胸抹蒜鹽放蒸盤',
      '電鍋外鍋2杯水',
      '跳起前5分鐘加花椰菜',
      '進食順序：先吃花椰菜（纖維）→ 雞胸（蛋白）→ 飯（碳水）',
    ],
    tips: '進食順序：纖維→蛋白→碳水，可降低餐後血糖 30-40%',
  },
  {
    id: 'dinner-salmon-cauliflower-rice',
    name: '檸檬鮭魚花椰菜飯',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 42, carbs: 48, fat: 12, calories: 468 },
    ingredients: [
      { name: '冷凍鮭魚排', amount: '150g' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '檸檬', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋加水',
      '鮭魚抹鹽放蒸盤，花椰菜鋪旁邊',
      '電鍋外鍋2杯水',
      '進食順序：先吃花椰菜 → 鮭魚（擠檸檬）→ 飯',
    ],
  },
  {
    id: 'dinner-egg-spinach-sweet-potato',
    name: '多蛋菠菜地瓜餐',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 35,
    macros: { protein: 40, carbs: 55, fat: 16, calories: 520 },
    ingredients: [
      { name: '雞蛋', amount: '5顆' },
      { name: '菠菜', amount: '150g' },
      { name: '地瓜', amount: '250g' },
      { name: '洋蔥', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '地瓜切塊放內鍋，蛋放蒸架',
      '電鍋外鍋1.5杯水',
      '跳起前3分鐘加菠菜和洋蔥絲',
      '進食順序：先吃菠菜洋蔥 → 水煮蛋 → 地瓜',
    ],
    tips: '地瓜含色氨酸轉化路徑：色氨酸→血清素→褪黑激素，晚餐吃助眠',
  },
  {
    id: 'dinner-chicken-dual-cruciferous',
    name: '雞胸雙花蔬菜盤',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 48, carbs: 42, fat: 5, calories: 405 },
    ingredients: [
      { name: '雞胸肉', amount: '160g' },
      { name: '冷凍綠花椰菜', amount: '100g' },
      { name: '菠菜', amount: '100g' },
      { name: '糙米', amount: '90g（生重）' },
      { name: '大蒜', amount: '3瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋',
      '雞胸切厚片抹蒜鹽，放蒸盤',
      '電鍋外鍋2杯水，跳起前5分鐘加花椰菜和菠菜',
      '進食順序：先吃蔬菜 → 雞胸 → 糙米飯',
    ],
  },
  {
    id: 'dinner-salmon-broccoli-avocado',
    name: '鮭魚酪梨花椰菜餐',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 40,
    macros: { protein: 41, carbs: 40, fat: 20, calories: 500 },
    ingredients: [
      { name: '冷凍鮭魚排', amount: '140g' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '酪梨', amount: '半顆' },
      { name: '糙米', amount: '80g（生重）' },
      { name: '檸檬', amount: '半顆' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋，鮭魚放蒸盤',
      '電鍋外鍋2杯水，跳起前5分鐘加花椰菜',
      '酪梨切片（不加熱）',
      '進食順序：先吃花椰菜 → 鮭魚+酪梨（擠檸檬）→ 飯',
    ],
    tips: '酪梨的健康脂肪幫助脂溶性維生素吸收',
  },
  {
    id: 'dinner-egg-cauliflower-garlic',
    name: '蒜蓉蛋花椰菜飯',
    mealSlot: 'dinner',
    cookingMethod: '電子鍋',
    prepTime: 35,
    macros: { protein: 42, carbs: 50, fat: 14, calories: 490 },
    ingredients: [
      { name: '雞蛋', amount: '4顆' },
      { name: '冷凍綠花椰菜', amount: '200g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '大蒜', amount: '4瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放電子鍋煮飯',
      '蛋和花椰菜放蒸架',
      '蒜切末，完成後撒在花椰菜上',
      '進食順序：先吃蒜蓉花椰菜 → 水煮蛋 → 飯',
    ],
  },
  {
    id: 'dinner-chicken-kimchi-spinach',
    name: '雞胸泡菜菠菜糙米',
    mealSlot: 'dinner',
    cookingMethod: '電鍋',
    prepTime: 45,
    macros: { protein: 47, carbs: 48, fat: 5, calories: 425 },
    ingredients: [
      { name: '雞胸肉', amount: '150g' },
      { name: '泡菜', amount: '80g' },
      { name: '菠菜', amount: '120g' },
      { name: '糙米', amount: '100g（生重）' },
      { name: '大蒜', amount: '2瓣' },
      { name: '碘鹽', amount: '適量' },
    ],
    steps: [
      '糙米放內鍋，雞胸抹蒜鹽放蒸盤',
      '電鍋外鍋2杯水',
      '跳起前3分鐘加菠菜',
      '雞胸切片，搭配泡菜食用',
      '進食順序：先吃菠菜+泡菜 → 雞胸 → 飯',
    ],
    tips: '泡菜提供活性乳酸菌，增強腸道微生物多樣性',
  },
];

// ─── 輪替邏輯 ───

function getDayOfYear(dateStr: string): number {
  const date = new Date(dateStr + 'T00:00:00');
  const startOfYear = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - startOfYear.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

export function getTodayRecipes(dateStr: string): DailyRecipes {
  const dayOfYear = getDayOfYear(dateStr);
  return {
    postWorkout: postWorkoutRecipes[dayOfYear % postWorkoutRecipes.length],
    lunch: lunchRecipes[dayOfYear % lunchRecipes.length],
    dinner: dinnerRecipes[dayOfYear % dinnerRecipes.length],
  };
}
